/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_snaprec_NativeScreenCapture */

#ifndef _Included_com_example_snaprec_NativeScreenCapture
#define _Included_com_example_snaprec_NativeScreenCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_snaprec_NativeScreenCapture
 * Method:    captureFrame
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_snaprec_NativeScreenCapture_captureFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
